### ISSUE TITLE
uvcvideo.ko驱动无法加载

### ISSUE THREAD

**Issue by lichq5** [orangepi-xunlong/OrangePiH5_kernel#2]
你好，我最近用orange pi prime装了从官方网站下载的安卓镜像。发现一个问题，在这个系统下无法识别我的usb摄像头。
我在终端上用ls /dev/v*命令也是查不到video的。然后我查了这个系统的驱动，发现在/system/vendor/modules目录下是有
uvcvideo.ko的驱动的。但是我尝试加载这个驱动的时候出错：
insmod: init_module 'uvcvideo.ko' failed (No such file or directory)
我用dmeg | grep uvc命令看了一下日志：
**uvcvideo: Unknown symbol vb2_vmalloc_memops (err 0)**
估计是这个驱动在编译的时候报错了。
能解释一下是怎么回事吗？解决的方法是什么？

**Comment by orangepi-xunlong** [comment]
您好，[最新的镜像](http://www.orangepi.cn/) USB 摄像头的驱动在插入USB摄像头后会自动加载，欢迎去官网下载测试。
