### ISSUE TITLE
spidev not available

### ISSUE THREAD

**Issue by sywong2000** [orangepi-xunlong/OrangePiH5_kernel#3]
I've purchased a OrangePi Zero Plus 2 and I've found the spidev is not available. It seemed the .config was missing the CONFIG_SPI_SPIDEV=y?

**Comment by orangepi-xunlong** [comment]
[This configuration](https://github.com/orangepi-xunlong/OrangePiH5_kernel/blob/dd3be1e9a3c36dc981416c0455921adc9c5a995c/arch/arm64/configs/orangepi_zeroplus2h5_defconfig#L1541) has been added, thanks!
