### ISSUE TITLE
dependencies of sst_storage.o.d not found

### ISSUE THREAD

**Issue by sywong2000** [orangepi-xunlong/OrangePiH5_kernel#4]
During compilation below error occurs:

**CC      drivers/misc/sst_storage/sst_storage.o
In file included from /root/OrangePiH5_kernel/include/linux/linkage.h:4:0,
                 from /root/OrangePiH5_kernel/include/linux/kernel.h:6,
                 from /root/OrangePiH5_kernel/drivers/misc/sst_storage/sst_storage.c:19:
/root/OrangePiH5_kernel/include/linux/compiler-gcc5.h:24:45: fatal error: opening dependency file drivers/misc/sst_storage/.sst_storage.o.d: No such file or directory**

It appears there's a problem on the drivers/misc/Makefile at the line:

_obj-$(CONFIG_SUNXI_SST_STORAGE) += sst_storage/sst_storage.o_

which I believe assumes a prebuild .o was already there but its not.

I've worked around to change the line to 
_obj-$(CONFIG_SUNXI_SST_STORAGE) += sst_storage/_

and then make a new Makefile under the folder drivers/misc/sst_storage/ which compiles the sst_storage.o

then the build is able to compile
You may want to update the source to fix this.
Thanks

**Comment by cengizIO** [comment]
Hello @sywong2000 

Please check if my PR is exactly what you did.

https://github.com/orangepi-xunlong/OrangePiH5_kernel/pull/5
